#!/usr/bin/env python3
"""Generate results/metacompressor_columnar_v2_report.md from micro-benchmark corpora."""

from __future__ import annotations

import tempfile
from pathlib import Path
from typing import Dict, List, Tuple

import metacompressor.corpus_template as ct
from metacompressor.corpus_template import (
    _MODE_COLUMNAR_V2,
    _MODE_RAW_TAR_ZSTD,
    _MODE_ROW_V1,
    compress_corpus_template_with_metrics,
)


def _write_corpus(root: Path, files: Dict[str, bytes]) -> None:
    for rel, data in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)


def _run_dataset(name: str, files: Dict[str, bytes]) -> Dict[str, object]:
    root = Path(tempfile.mkdtemp(prefix="mc_colv2_"))
    _write_corpus(root, files)
    old_th = ct._CORPUS_FALLBACK_THRESHOLD
    ct._CORPUS_FALLBACK_THRESHOLD = float("inf")
    try:
        _, metrics = compress_corpus_template_with_metrics(root)
    finally:
        ct._CORPUS_FALLBACK_THRESHOLD = old_th

    tar = int(metrics["tarzstd_size"])
    v1 = int(metrics["columnar_v1_size"])
    v2 = int(metrics["columnar_size"])
    final = str(metrics["final_selected_mode"])
    v2_vs_v1 = v1 - v2
    if tar == 0:
        final_vs_tar = 0.0
    else:
        final_bytes = int(metrics["compressed_size"])
        final_vs_tar = 100.0 * (final_bytes - tar) / tar

    if final == _MODE_RAW_TAR_ZSTD:
        winner = "TAR+ZSTD (raw fallback)"
    elif final == _MODE_COLUMNAR_V2 and metrics["compressed_size"] < tar:
        winner = "MC columnar v2"
    elif final == _MODE_ROW_V1:
        winner = "MC row template"
    else:
        winner = "MC columnar v2" if final == _MODE_COLUMNAR_V2 else final

    return {
        "dataset": name,
        "tar": tar,
        "v1": v1,
        "v2": v2,
        "final": final,
        "v2_vs_v1": v2_vs_v1,
        "final_vs_tar_pct": final_vs_tar,
        "winner": winner,
        "col_savings": int(metrics.get("columnar_v2_savings_vs_v1_columns", 0)),
    }


def _datasets() -> List[Tuple[str, Dict[str, bytes]]]:
    line = b'{"service":"api","status":200,"request_id":"user-%d","path":"/p"}\n'
    prefixed_small = {
        "x.ndjson": b"".join(b"2026-05-04T12:00:00Z " + (line % i) for i in range(50))
    }
    plain_small = {"x.ndjson": b"".join(line % i for i in range(50))}
    plain_large = {"x.ndjson": b"".join(line % i for i in range(500))}
    mixed = {
        "a.log": b"".join(
            (
                b"2026-01-01T00:00:00Z service=api "
                b"trace=%016x latency_ms=%d\n" % (i, i % 200)
            )
            for i in range(120)
        )
    }
    nginx = {
        "access.log": b"".join(
            (
                b'127.0.0.1 - - [01/Jan/2026:12:00:%02d +0000] "GET /path/%d HTTP/1.1" 200 %d\n'
                % (i % 60, i, 100 + (i % 50))
            )
            for i in range(200)
        )
    }
    highcard = {
        "h.log": b"".join(
            b"INFO id=%032x msg=ok\n" % (i * 7919 + 17,) for i in range(150)
        )
    }
    many_small: Dict[str, bytes] = {}
    for i in range(80):
        many_small[f"shard/{i:04d}.txt"] = b"OK row=%d\n" % i

    return [
        ("prefixed NDJSON n=50", prefixed_small),
        ("plain NDJSON n=50", plain_small),
        ("plain NDJSON n=500", plain_large),
        ("mixed microservice-like", mixed),
        ("nginx-like access n=200", nginx),
        ("high-cardinality ids n=150", highcard),
        ("many-small-files n=80", many_small),
    ]


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    out_path = repo / "results" / "metacompressor_columnar_v2_report.md"

    rows: List[Dict[str, object]] = []
    for title, files in _datasets():
        rows.append(_run_dataset(title, files))

    ndjson_improved = any(
        r["dataset"].startswith(("prefixed NDJSON", "plain NDJSON"))
        and int(r["col_savings"]) > 0
        for r in rows
    )

    lines = [
        "# MetaCompressor Columnar Encoding v2 Report",
        "",
        "Generated by `scripts/generate_columnar_v2_report.py`.",
        "",
        "Column **v1** profile = raw + varint + delta only (no dictionary/RLE).",
        "**v2** profile = v1 candidates plus dictionary + RLE; smallest lossless encoding wins per column.",
        "Corpora use `_CORPUS_FALLBACK_THRESHOLD = inf` for this table so template modes are not replaced by raw TAR+ZSTD.",
        "",
        "| Dataset | TAR+ZSTD | Columnar v1 | Columnar v2 | Final selected | v2 vs v1 (bytes) | Final vs TAR+ZSTD (%) | Winner |",
        "| ------- | -------: | ----------: | ----------: | ------------- | ---------------: | --------------------: | ------ |",
    ]
    for r in rows:
        lines.append(
            "| {dataset} | {tar:,} | {v1:,} | {v2:,} | `{final}` | {v2v1:,} | {ftp:+.2f}% | {winner} |".format(
                dataset=r["dataset"],
                tar=r["tar"],
                v1=r["v1"],
                v2=r["v2"],
                final=r["final"],
                v2v1=r["v2_vs_v1"],
                ftp=r["final_vs_tar_pct"],
                winner=r["winner"],
            )
        )

    lines += [
        "",
        "## Column-level v2 vs v1 (msgpack column payloads only)",
        "",
        "Positive `columnar_v2_savings_vs_v1_columns` in metrics means v2 column blobs are smaller than v1 blobs summed over all encoded columns.",
        "",
    ]
    for r in rows:
        lines.append(
            "- **{ds}**: column payload savings (v1−v2) = **{s:,}** bytes".format(
                ds=r["dataset"], s=int(r["col_savings"])
            )
        )

    verdict = "COLUMNAR_V2_VALIDATED"
    reasons: List[str] = []
    if not ndjson_improved:
        reasons.append(
            "NDJSON micro-corpus did not show positive column-level v1−v2 savings"
        )
    if reasons:
        verdict = "COLUMNAR_V2_PARTIAL\nReason: " + "; ".join(reasons)

    lines += [
        "",
        "## Verdict",
        "",
        "```text",
        verdict,
        "```",
        "",
        "## Notes",
        "",
        "- Full `pytest` and lossless round-trip are enforced in CI; re-run `pytest metacompressor/tests` after changes.",
        "- `mc compare-dir` prints extended columnar v2 metrics when using corpus-template.",
        "",
    ]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
